In [1]:
from qutip import *

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image

In [43]:
#Image(filename='chirped_mirrors_en-orig-1000-418-7916cde4.webp')

#### Creating and inspecting objects with #Qobj# class constructor 

In [44]:
q = Qobj([[1], [0]]); q1 = Qobj([[1, 0]]); q2 = Qobj([[1, 0], [0, 1]]); q3 = Qobj([[1, 0, 0, 0], 
          [0, 0, 0, 0], 
          [0, 0, 0, 0], 
          [0, 0, 0, 1]])
print(q , q1, q2, q3)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]] Quantum object: dims=[[1], [2]], shape=(1, 2), type='bra', dtype=Dense
Qobj data =
[[1. 0.]] Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]] Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [51]:
q3.isherm

True

In [55]:
q3.shape

(4, 4)

In [60]:
q.type, q2.type #ket, Operator

('ket', 'oper')

In [61]:
q3.full()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [65]:
q3.dims

[[4], [4]]

In [ ]:
# Qobj instances for calculations